### ISSUE TITLE
instant submissions

### ISSUE THREAD

**Issue by thorie7912** [thorie7912/afb-public#41]
Allow for a workflow where submissions are expected immediately, rather than full pitch+approve cycle. 

This is a faster workflow, good for quick tasks or tasks that allow multiple submissions, but not good for large tasks or one-time tasks because there is a much higher chance that hard work will be done, but won't be accepted.

1. asker creates a task
2. tasker submits their work immediately
3. asker is notified that work was submitted, but it is hidden
4. asker pays escrow to see the results
5. asker confirms the work is good, and releases escrow
6. tasker receives payment

If on step 5, asker is unhappy, then he can initiate a mutual cancel OR he can initiate a dispute.
If on step 6, tasker didn't receive payment because the other side wants to cancel, he can also initiate a dispute.

Just like in normal escrow, arbitration will decide who will get what % of the funds in this case. Typically judgment is 50/50 if both parties have reasonable arguments.

**Comment by RyanMilb** [comment]
While in step 5, is the asker able to message the worker letting the worker resubmit?

**Comment by RyanMilb** [comment]
Also, this belongs in a second task, but as an ASKER, I would like the option for all responses to be public. I realize this is an edge case. Just wondering how far along the roadmap it might be.

**Comment by thorie7912** [comment]
Yes, the worker can resubmit in step 5. Funds are locked in escrow until the asker is happy.

**Comment by RyanMilb** [comment]
Sounds good. Fits my needs :)

**Comment by thorie7912** [comment]
I've implemented this as an "Early Confirmation" button that appears after an offer is accepted. This skips waiting for the tasker to mark as delivered. You can payout immediately instead.
