### ISSUE TITLE
Anotehr dark mode issue 

### ISSUE THREAD

**Issue by RyanMilb** [thorie7912/afb-public#44]
![screenshot from 2018-11-14 02-08-43](https://user-images.githubusercontent.com/1234177/48436911-88caff00-e7b2-11e8-8361-111c0587a569.png)

Red text is really hard to read on dark mode.

**Comment by thorie7912** [comment]
Fixed in commit 21ed1f0c18fc97a7499b7e5e21b1b3787846146f

(ctrl-shift-r to reload css files in browser)
