### ISSUE TITLE
get-invoice erroring 500

### ISSUE THREAD

**Issue by fiatjaf** [thorie7912/afb-public#61]
Trying to pay an escrow invoice, the invoice is never generated, the call to `https://ask.for-bitcoin.com/payment/get-invoice?postId=105&offerId=278` gets repeated unending and fails with code 500 and the message: `Sorry, we've encountered an error. Please contact support so we can investigate this issue.`, the invoice text box keeps saying "Generating invoice...".

**Comment by thorie7912** [comment]
Hey, this might be due to me restarting the node. Let me investigate.

**Comment by thorie7912** [comment]
Yep, the node was restarted and needed to be reconnected. Should be working now, let me know otherwise.
